language: ruby
rvm:
  - 1.9.2
  - 1.9.3
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - psql -c 'create database rcheckin_test;' -U postgres
  - cp config/database.postgresql.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - bundle exec cucumber
  - bundle exec rspec spec/
