language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install:
  - git submodule update --init --recursive
before_script:
  - bundle install --gemfile faye/Gemfile
  - thin -p 9292 -c faye/ -R config.ru -P ../tmp/pids/faye.pid start &
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rake db:initialize_config
  - mysql -e 'create database rcheckin_test'
  - psql  -c 'create database rcheckin_test' -U postgres
script:
  - "export DISPLAY=:99.0 && RAILS_ENV=test bundle exec rake db:migrate"
  - "export DISPLAY=:99.0 && bundle exec cucumber"
  - "export DISPLAY=:99.0 && bundle exec rspec spec/"
  - thin stop -P tmp/pids/faye.pid
