language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - "export DISPLAY=:99.0 && RAILS_ENV=test bundle exec rake db:migrate"
  - "export DISPLAY=:99.0 && bundle exec cucumber"
  - "export DISPLAY=:99.0 && bundle exec rspec spec/"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rake db:initialize_config
  - mysql -e 'create database rcheckin_test'
  - psql  -c 'create database rcheckin_test' -U postgres
