common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password:

development:
  <<: *common
  database: rcheckin_development

test: &TEST
  <<: *common
  database: rcheckin_test

production:
  <<: *common
  database: rcheckin

cucumber:
  <<: *TEST
